### PR TITLE
[TF-1032] Update `engines` & `devEngines` to version 16

### PR DESCRIPTION
**Pull request by MohammadxAli**

### CODE REVIEW

**Review by oleg-semyonov — CHANGES_REQUESTED** [review]
Can you please bump the `npm` version to v8 as well? And do the same for all other PRs :)

**Comment by MohammadxAli** [comment]
@oleg-semyonov Sure! on it :)

**Review by oleg-semyonov — APPROVED** [review]
Thanks! Please do the same update on other PRs, you can merge them straight away.

Also, could you update the settings in the Vercel theme projects to use Node 16.x?
image

**Comment by MohammadxAli** [comment]
@oleg-semyonov Yeap! will update them on Vercel thanks for letting me know :)

**Pull request merged**
