### PR TITLE
[TF-949] implemented new contact section design

### PR DESCRIPTION
**Pull request by Gichohi-Simon**

### CODE REVIEW

**Review by oleg-semyonov — CHANGES_REQUESTED** [review]
Hmm, I just noticed that the design is inconsistent - on top of the artboard the avatar is to the left of the text, and on the bottom part it's above, the way you implemented it here.

This doesn't feel right. Until Hugo is back, I guess we should ask Al to help choose one variant over another.

Once the design is settled, please add screenshots of each design variation implemented in your code to the PR description (e.g. with or without avatar, with long email, etc.), so that we can evaluate that all cases are covered properly.

**Comment by Gichohi-Simon** [comment]
okay 👍

**Comment by Gichohi-Simon** [comment]
mobile screen.

mobile

tablet screen.

tablet

desktop screen.

desktop

**Review by oleg-semyonov — CHANGES_REQUESTED** [review]
This doesn't look right.

In addition to code review comments, here are some visual bugs:

1) The font size and weight is not correct. Check with Figma design
Screen Shot 2022-08-02 at 10 01 09

2) On tablet, the text is not vertically centered with the avatar
image

Overall, I see lots of small differences from the Figma design (e.g. avatar size, spacing). Please check thoroughly and make sure your layout matches the design.

**Comment by Gichohi-Simon** [comment]
Thanks for the insight let me make the changes👍🏾

**Pull request closed without merging**
