### PR TITLE
[TF-990] added ssr to header to fix the css loading bug

### PR DESCRIPTION
**Pull request by Gichohi-Simon**

### CODE REVIEW

**Review by oleg-semyonov — CHANGES_REQUESTED** [review]
This is not a solution I'd expect.

We can't afford to introduce layout shifts to our newsrooms.

**Comment by Gichohi-Simon** [comment]
All right, The other solution I had in mind was to hide the CSS while it's loading, and then show it while it has already loaded and marked it as important in the stylesheet. 
However, I was not so confident about this solution. Should I try this so that you can see what the code looks like?

**Comment by Gichohi-Simon** [comment]
incorrectly named my commit message, but what I meant was that I tried a CSS solution instead of an SSR-based solution. Kindly check the fixing lint error commit for all the changes I made.

**Review by oleg-semyonov — COMMENTED** [review]
This is still not an optimal solution.
If you'd want to go with CSS approach, the proper solution would be to create an inline `style` tag in the document that would reset the button styles (better yet, inline the `modern-normalize` stylesheets).

The funny thing is that I'm trying to reproduce the issue on the production environment and the styles are loading just fine 🤔 

I think it's better to close this PR and think on the ticket a bit more

**Comment by Gichohi-Simon** [comment]
Okay, let me try and solve it as per your suggestions

**Pull request closed without merging**
